[package]
name = "primes"
version = "0.1.0"
authors = ["EricGlover <horatiofox0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
